import type { Metadata } from "next";
import localFont from "next/font/local";
import { Joti_One } from "next/font/google"
import "./globals.css";
import Header from "@/components/header";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});
const joti_One = Joti_One({
  subsets: ["latin"],
  weight: "400",
  variable: "--font-joti_One",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${joti_One.variable} antialiased`}
      >
        <Header/>
        {children}
      </body>
    </html>
  );
}
